name: Build Fetchy Fetch Boi
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Load global environment variables
        run: cat .github/config/global.env >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: build fetchy fetch boi
        run: npm run build-fetchy-fetch-boi
