name: Run Fetchy Fetch Boi
on:
  schedule:
    # This will run fetchy every 5 mins with an offset of 3 min
    - cron: "3-59/5 * * * *"
  pull_request:
  push:
    branches:
      - main

jobs:
  fetchy:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Load global environment variables
        run: cat .github/config/global.env >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Fetchy
        run: npm run fetch-boi
      - uses: EndBug/add-and-commit@v7
        if: ${{ github.event_name == 'schedule' }}
        with:
          default_author: github_actions
          message: "Adding/Updating the latest MoH Data"
