name: Run Fetchy Fetch Boi
on:
  schedule:
    # This will run fetchy every 5 mins
    - cron: "*/5 * * * *"
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Load global environment variables
        run: cat .github/config/global.env >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Fetchy
        run: npm run fetch-boi
        # Just testing to see if the git checkout will be detached or not
      - name: Git status
        if: ${{ github.event_name == 'schedule' }}
        run: git status
